name: Deploy Images to GHCR

env:
  DOTNET_VERSION: '6.0.x'

on:
  push:
    branches:
      - main
    paths:
      - apps/api/**
  workflow_dispatch:

jobs:
  push_to_registries:
    name: Push Docker images to GHCR
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # --- Metadata for firecrawl image (apps/api) ---
      - name: Extract metadata for firecrawl
        id: meta_api
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/firecrawl
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}

      # --- Build and push firecrawl image ---
      - name: Build and push firecrawl image
        uses: docker/build-push-action@v5
        with:
          context: ./apps/api
          tags: ${{ steps.meta_api.outputs.tags }}
          labels: ${{ steps.meta_api.outputs.labels }}
          push: true
