name: Publish Docker images (amd64)

on:
  push:
    tags:
      - 'v*.*.*'  # 匹配类似 v1.0.0 的 tag
  workflow_dispatch:
    inputs:
      name:
        description: 'reason'
        required: false

jobs:
  push_to_registries:
    name: Push Docker images to GHCR
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # --- Metadata for firecrawl image (apps/api) ---
      - name: Extract metadata for firecrawl
        id: meta_api
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/firecrawl
          tags: |
            type=ref,event=tag
            type=sha

      # --- Metadata for firecrawl-playwright image (apps/playwright-service) ---
      - name: Extract metadata for firecrawl-playwright
        id: meta_playwright
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/firecrawl-playwright
          tags: |
            type=ref,event=tag
            type=sha

      # --- Build and push firecrawl image ---
      - name: Build and push firecrawl image
        uses: docker/build-push-action@v5
        with:
          context: ./apps/api
          tags: ${{ steps.meta_api.outputs.tags }}
          labels: ${{ steps.meta_api.outputs.labels }}
          push: true

      # --- Build and push firecrawl-playwright image ---
      - name: Build and push firecrawl-playwright image
        uses: docker/build-push-action@v5
        with:
          context: ./apps/playwright-service-ts
          tags: ${{ steps.meta_playwright.outputs.tags }}
          labels: ${{ steps.meta_playwright.outputs.labels }}
          push: true